### PR TITLE
Create LEARN.md

### LINKED ISSUE #30: Missing learn.md_[Documentation Bug]:
### Describe the bug ✍️

Learn.md file is missing in our current repository.

@roy7077 assign this issue to me I will create it 

### Provide step by step information reproduce the bug 📄

A learn.md file in GitHub is often used as a documentation file to provide learning resources, instructions, or a guide to help users understand how to use the repository or learn specific concepts related to the project. It's similar to a README.md but specifically focused on educational content. Below is a detailed guide on how to create and use a learn.md file in a GitHub repository.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Meetjain1**
## PR Description 📜

created learn.md file from scratch
Fixes #30 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Durgesh4993 have a look on this pr . Thanks

**Comment by Meetjain1** [comment]
@roy7077 @Durgesh4993  have a look on this pr . Thanks

**Comment by Meetjain1** [comment]
@roy7077 @Durgesh4993  have a look on this pr . Thanks

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
